version: '3.4'
services:
  service:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - '8080:8080'
  prometheus:
    image: prom/prometheus
    expose:
    - '9090'
    volumes:
    - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
  grafana:
    image: grafana/grafana:9.3.6
    ports:
      - "3000:3000"
    volumes:
      - './grafana/grafana.ini:/etc/grafana/grafana.ini'
      - './grafana/default.yml:/etc/grafana/provisioning/dashboards/default.yml'
      - './grafana/datasource.yml:/etc/grafana/provisioning/datasources/demo.yaml'
      - './grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json'
